export type {
  ActiveShortNameConflict,
  CanonicalPatch,
  CanonicalPatchOperation,
  Capability,
  CapabilityRequirement,
  Command,
  CommandContext,
  CommandContextSelection,
  CommandContextSurface,
  CommandContextTarget,
  CommandDispatcher,
  CommandDispatcherExecution,
  CommandDispatcherResult,
  CommandHandler,
  CommandHandlerExecution,
  CommandManifest,
  CommandMenuGroup,
  CommandMenuPresentation,
  CommandRegistry,
  CommandToolbarPresentation,
  CommandWhen,
  CommandContribution,
  ContributionInspectorCapabilityEntry,
  ContributionInspectorContributionEntry,
  ContributionInspectorModel,
  ContributionInspectorPackageEntry,
  ContributionManifest,
  ContributionPackageDependency,
  ContributionRegistry,
  ContributionRegistryContext,
  ContributionRegistryPackage,
  ContributionRegistryResolvedDependency,
  ContributionRegistryResolution,
  Diagnostic,
  DiagnosticOrigin,
  DiagnosticRelatedInformation,
  DocumentCapabilityActivation,
  DocumentContributionContext,
  DocumentContributionResolverOptions,
  EditorCapabilityId,
  EditorDiagnosticBridge,
  LanguageDefinition,
  LanguageId,
  MarkdownFenceHandlerContribution,
  PipelineContribution,
  PipelineValue,
  RegisteredCapability,
  ResolvedCapability,
  ResolvedCommand,
  ResolvedContribution,
  ResourceBadgeToken,
  ResourceBundledProvenance,
  ResourceCapabilityId,
  ResourceCopyProvenance,
  ResourceFacts,
  ResourceGeneratedProvenance,
  ResourceKind,
  ResourcePredicate,
  ResourceProvenance,
  ResourceRef,
  ResourceRepresentation,
  Severity,
  SourcePosition,
  SourceRange,
  SurfaceContribution,
} from './types';
export {
  capabilityStates,
  contributionKinds,
  contributionRegistryPackageStatuses,
  editorCapabilityIds,
  languageDefinitions,
  resourceBadgePlacements,
  resourceCapabilityIds,
  resourceKinds,
  resourceRepresentations,
} from './constants';
export {
  createCanonicalContributionId,
  deriveCapabilityLocalName,
  deriveContributionLocalName,
} from './identity';
export {
  createCanonicalPatch,
  createDiagnostic,
  createPipelineValue,
  createResourceBadgeToken,
  createResourceFacts,
  createResourcePredicate,
  createResourceRef,
  createSourcePosition,
  createSourceRange,
  getLanguageDefinition,
  getResourceRepresentation,
  hasResourceCapability,
  inferLanguageId,
  inferResourceRepresentation,
  matchesResourcePredicate,
} from './resources';
export {
  createCommand,
  createCommandContext,
  createCommandDispatcher,
  createCommandManifest,
  createCommandRegistry,
  matchesCommandContext,
  resolveCommandState,
} from './commands';
export {
  contributions,
  createCapability,
  createContributionInspectorModel,
  createContributionManifest,
  createContributionRegistry,
  createMarkdownFenceHandlerContribution,
  createPipelineContribution,
  createSurfaceContribution,
  defaultContributionManifest,
  resolveDocumentContributionContext,
} from './contributions';
