import { createCapability, createContributionManifest, createDiagnostic } from '@textforge/core';

export const pipelineValueKinds = [
  'text',
  'html',
  'svg',
  'png',
  'json',
  'yaml',
  'workspace-resource',
  'diagnostics',
];

export const generatedResourceFormats = ['svg', 'png', 'html'];
export const pipelineCapabilities = [
  createCapability('@textforge/pipeline/capability/run', {
    description: 'Run local pipeline steps over bundled TextForge values.',
    defaultActive: true,
    scope: 'document',
  }),
];

function createPipelineDiagnostic(code, message, severity = 'information', overrides = {}) {
  return createDiagnostic(message, severity, {
    code,
    origin: {
      packageId: '@textforge/pipeline',
      subsystem: 'pipeline',
      ...overrides.origin,
    },
    ...overrides,
  });
}

export function createGeneratedResourceDescriptor(input = {}) {
  if (!input.path) {
    throw new Error('Generated resources require a workspace path.');
  }

  const representation = input.representation ?? (typeof input.text === 'string' ? 'text' : 'bytes');
  if (representation !== 'text' && representation !== 'bytes') {
    throw new Error(`Unsupported generated resource representation: ${representation}`);
  }

  if (representation === 'text' && typeof input.text !== 'string') {
    throw new Error(`Generated text resource ${input.path} is missing text content.`);
  }

  if (representation === 'bytes' && !(input.bytes instanceof Uint8Array)) {
    throw new Error(`Generated byte resource ${input.path} is missing byte content.`);
  }

  return {
    kind: 'generated-resource',
    path: input.path,
    title: input.title,
    representation,
    mimeType: input.mimeType,
    languageId: input.languageId,
    text: representation === 'text' ? input.text : undefined,
    bytes: representation === 'bytes' ? new Uint8Array(input.bytes) : undefined,
    format: input.format,
    pipelineId: input.pipelineId,
    sourceResourceId: input.sourceResourceId,
    sourcePath: input.sourcePath,
    sourceUpdatedAt: input.sourceUpdatedAt,
    blockId: input.blockId,
    blockKind: input.blockKind,
    generatedAt: input.generatedAt ?? new Date().toISOString(),
    metadata: input.metadata ? { ...input.metadata } : undefined,
  };
}

export function createPipelineStep(id, overrides = {}) {
  return {
    id,
    contributionId: overrides.contributionId ?? id,
    localName: overrides.localName,
    capabilities: overrides.capabilities ?? ['@textforge/pipeline/capability/run'],
    defaultActive: overrides.defaultActive ?? true,
    inputKind: overrides.inputKind ?? 'text',
    outputKind: overrides.outputKind ?? 'html',
    description: overrides.description,
    run: overrides.run ?? (async ({ input }) => ({ output: input })),
  };
}

export function createPipelineRegistry(initialSteps = []) {
  const steps = new Map();

  function register(step) {
    const normalized = createPipelineStep(step.id, step);
    steps.set(normalized.id, normalized);
    return registry;
  }

  const registry = {
    register,
    get(stepId) {
      return steps.get(stepId);
    },
    list() {
      return [...steps.values()];
    },
  };

  for (const step of initialSteps) {
    register(step);
  }

  return registry;
}

function inferValueKind(value, fallback) {
  if (value?.kind) {
    return value.kind;
  }
  return fallback ?? 'text';
}

export function createPipelineRunner(options = {}) {
  const registry = options.registry ?? createPipelineRegistry();
  const now = options.now ?? (() => new Date().toISOString());

  return {
    registry,
    async run(input, runOptions = {}) {
      const stopOnError = runOptions.stopOnError ?? true;
      const diagnostics = [];
      const generatedResources = [];
      const trace = [];
      let current = input;
      let failed = false;

      const steps = (runOptions.steps ?? []).flatMap((step) => {
        if (typeof step === 'string') {
          const resolved = registry.get(step);
          if (!resolved) {
            diagnostics.push(createPipelineDiagnostic(
              'pipeline.step.missing',
              `Unknown pipeline step: ${step}`,
              'error',
              {
                origin: {
                  pipelineStepId: step,
                },
              },
            ));
            failed = true;
            trace.push({
              stepId: step,
              contributionId: step,
              inputKind: inferValueKind(current, 'text'),
              outputKind: inferValueKind(current, 'text'),
              startedAt: now(),
              finishedAt: now(),
              status: 'failed',
              diagnosticsCount: 1,
              generatedResourceCount: 0,
            });
            return [];
          }
          return [resolved];
        }
        return [createPipelineStep(step.id, step)];
      });

      if (failed && stopOnError) {
        return {
          ok: false,
          value: current,
          diagnostics,
          generatedResources,
          trace,
        };
      }

      for (const step of steps) {
        const startedAt = now();
        try {
          const result = await step.run({
            input: current,
            context: runOptions.context,
            now,
            diagnostics: [...diagnostics],
            trace: [...trace],
          }) ?? {};

          const nextOutput = result.output ?? current;
          const stepDiagnostics = result.diagnostics ?? [];
          const stepGeneratedResources = (result.generatedResources ?? []).map((resource) =>
            createGeneratedResourceDescriptor(resource));
          diagnostics.push(...stepDiagnostics);
          generatedResources.push(...stepGeneratedResources);
          trace.push({
            stepId: step.id,
            contributionId: step.contributionId ?? step.id,
            inputKind: inferValueKind(current, step.inputKind),
            outputKind: inferValueKind(nextOutput, step.outputKind),
            startedAt,
            finishedAt: now(),
            status: 'done',
            diagnosticsCount: stepDiagnostics.length,
            generatedResourceCount: stepGeneratedResources.length,
          });
          current = nextOutput;
        } catch (error) {
          failed = true;
          diagnostics.push(createPipelineDiagnostic(
            'pipeline.step.failed',
            error?.message ?? `Pipeline step failed: ${step.id}`,
            'error',
            {
              origin: {
                contributionId: step.contributionId ?? step.id,
                pipelineStepId: step.id,
              },
            },
          ));
          trace.push({
            stepId: step.id,
            contributionId: step.contributionId ?? step.id,
            inputKind: inferValueKind(current, step.inputKind),
            outputKind: step.outputKind ?? inferValueKind(current, 'text'),
            startedAt,
            finishedAt: now(),
            status: 'failed',
            diagnosticsCount: 1,
            generatedResourceCount: 0,
          });
          if (stopOnError) {
            break;
          }
        }
      }

      return {
        ok: !failed,
        value: current,
        diagnostics,
        generatedResources,
        trace,
      };
    },
  };
}

export function createPipelineContributionManifest(pipelines = []) {
  return createContributionManifest('@textforge/pipeline', {
    capabilities: pipelineCapabilities,
    pipelines: pipelines.map((step) => createPipelineStep(step.id, step)),
  });
}

export const contributions = createPipelineContributionManifest();
