export function createGeneratedResourceDescriptor(input = {}) {
  if (!input.path) {
    throw new Error('Generated resources require a workspace path.');
  }

  const representation = input.representation ?? (typeof input.text === 'string' ? 'text' : 'bytes');
  if (representation !== 'text' && representation !== 'bytes') {
    throw new Error(`Unsupported generated resource representation: ${representation}`);
  }

  if (representation === 'text' && typeof input.text !== 'string') {
    throw new Error(`Generated text resource ${input.path} is missing text content.`);
  }

  if (representation === 'bytes' && !(input.bytes instanceof Uint8Array)) {
    throw new Error(`Generated byte resource ${input.path} is missing byte content.`);
  }

  return {
    kind: 'generated-resource',
    path: input.path,
    title: input.title,
    representation,
    mimeType: input.mimeType,
    languageId: input.languageId,
    text: representation === 'text' ? input.text : undefined,
    bytes: representation === 'bytes' ? new Uint8Array(input.bytes) : undefined,
    format: input.format,
    pipelineId: input.pipelineId,
    sourceResourceId: input.sourceResourceId,
    sourcePath: input.sourcePath,
    sourceUpdatedAt: input.sourceUpdatedAt,
    blockId: input.blockId,
    blockKind: input.blockKind,
    generatedAt: input.generatedAt ?? new Date().toISOString(),
    metadata: input.metadata ? { ...input.metadata } : undefined,
  };
}
